### ISSUE TITLE
jruby 1.7.13 support

### ISSUE THREAD

**Issue by mooreniemi** [coderanger/yard-classmethods#1]
I tried using your gem in jruby 1.7.13 and had the below failure, while it worked perfectly in ruby 2.1.3:

```
C02LX2KVFD58:~/work repos/core-resource-rb/ capi-91 λ yard doc --plugin classmethods
/Users/amooreniemi/.rvm/gems/jruby-1.7.13@global/gems/yard-0.8.7.6/bin/../lib/yard/tags/directives.rb:352 warning: already initialized constant SCOPE_MATCH
[error]: Invalid configuration file, using default options.
[error]: NoMethodError: undefined method `prepend' for YARD::Handlers::Ruby::ModuleHandler:Class
[error]: Stack trace:
    /Users/amooreniemi/.rvm/gems/jruby-1.7.13/gems/yard-classmethods-1.0.0/lib/yard_classmethods.rb:58:in `(root)'
    org/jruby/RubyKernel.java:1065:in `require'
    /Users/amooreniemi/.rvm/gems/jruby-1.7.13/gems/yard-classmethods-1.0.0/lib/yard-classmethods.rb:1:in `(root)'
    org/jruby/RubyKernel.java:1065:in `require'
    /Users/amooreniemi/.rvm/gems/jruby-1.7.13/gems/yard-classmethods-1.0.0/lib/yard-classmethods.rb:17:in `(root)'
    /Users/amooreniemi/.rvm/gems/jruby-1.7.13@global/gems/yard-0.8.7.6/lib/yard/config.rb:1:in `(root)'

Files:           2
Modules:         2 (    1 undocumented)
Classes:         1 (    1 undocumented)
Constants:       0 (    0 undocumented)
Methods:        21 (    2 undocumented)
 83.33% documented
```

**Comment by coderanger** [comment]
Sounds like JRuby doesn't support `Module#prepend`? If not there isn't much I can do, it would make things a lot messier to not use it.
